# Generated by Django 4.1.2 on 2023-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_mails_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='ReadAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
